//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бронь
    {
        public int Код { get; set; }
        public Nullable<int> Сотрудник { get; set; }
        public Nullable<double> Стоимость { get; set; }
        public Nullable<System.DateTime> Дата_начала_бронирования { get; set; }
        public Nullable<System.DateTime> Дата_конца_бронирования { get; set; }
        public Nullable<int> Гость { get; set; }
        public Nullable<int> Код_номера { get; set; }
        public Nullable<int> Количество_дней { get; set; }
    
        public virtual Гость Гость1 { get; set; }
        public virtual Номер Номер { get; set; }
        public virtual Сотрудник Сотрудник1 { get; set; }
    }
}
