//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Номер
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Номер()
        {
            this.Бронь = new HashSet<Бронь>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Номер1 { get; set; }
        public Nullable<int> Статус_номера { get; set; }
        public string Вместимость { get; set; }
        public Nullable<int> Цена_за_ночь { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бронь> Бронь { get; set; }
        public virtual Статус_номера Статус_номера1 { get; set; }
    }
}
